/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view;

import javax.swing.ImageIcon;

/**
 *
 * @author ACER
 */
public class FrmMain extends javax.swing.JFrame {

	/**
	 * Creates new form FrmMain
	 */

	private ImageIcon slika;

	public FrmMain() {
		initComponents();
		postaviSliku();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jMenuItem1 = new javax.swing.JMenuItem();
		lblSlika = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		mRadnik = new javax.swing.JMenu();
		miPrikaziSveRadnike = new javax.swing.JMenuItem();
		miKreirajNovogRadnika = new javax.swing.JMenuItem();
		mMasinaIliAlat = new javax.swing.JMenu();
		miPrikaziSveMasineIliAlat = new javax.swing.JMenuItem();
		miKreirajNovuMasinuIliAlat = new javax.swing.JMenuItem();
		mi = new javax.swing.JMenu();
		miPrikaziSveReverse = new javax.swing.JMenuItem();
		miKreirajNoviRevers = new javax.swing.JMenuItem();

		jMenuItem1.setText("jMenuItem1");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setMinimumSize(new java.awt.Dimension(765, 491));

		mRadnik.setText("Radnik");
		mRadnik.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

		miPrikaziSveRadnike.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		miPrikaziSveRadnike.setText("Prikazi sve");
		miPrikaziSveRadnike.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				miPrikaziSveRadnikeActionPerformed(evt);
			}
		});
		mRadnik.add(miPrikaziSveRadnike);

		miKreirajNovogRadnika.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		miKreirajNovogRadnika.setText("Kreiraj novog");
		miKreirajNovogRadnika.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				miKreirajNovogRadnikaActionPerformed(evt);
			}
		});
		mRadnik.add(miKreirajNovogRadnika);

		jMenuBar1.add(mRadnik);

		mMasinaIliAlat.setText("Masina ili Alat");
		mMasinaIliAlat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

		miPrikaziSveMasineIliAlat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		miPrikaziSveMasineIliAlat.setText("Prikazi sve");
		miPrikaziSveMasineIliAlat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				miPrikaziSveMasineIliAlatActionPerformed(evt);
			}
		});
		mMasinaIliAlat.add(miPrikaziSveMasineIliAlat);

		miKreirajNovuMasinuIliAlat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		miKreirajNovuMasinuIliAlat.setText("Kreiraj novu Masinu ili Alat");
		miKreirajNovuMasinuIliAlat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				miKreirajNovuMasinuIliAlatActionPerformed(evt);
			}
		});
		mMasinaIliAlat.add(miKreirajNovuMasinuIliAlat);

		jMenuBar1.add(mMasinaIliAlat);

		mi.setText("Revers");
		mi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

		miPrikaziSveReverse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		miPrikaziSveReverse.setText("Prikazi sve");
		miPrikaziSveReverse.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				miPrikaziSveReverseActionPerformed(evt);
			}
		});
		mi.add(miPrikaziSveReverse);

		miKreirajNoviRevers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		miKreirajNoviRevers.setText("Kreiraj novi");
		miKreirajNoviRevers.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				miKreirajNoviReversActionPerformed(evt);
			}
		});
		mi.add(miKreirajNoviRevers);

		jMenuBar1.add(mi);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap()
						.addComponent(lblSlika, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap()
						.addComponent(lblSlika, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
						.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void miKreirajNoviReversActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_miKreirajNoviReversActionPerformed
		FrmNoviRevers frmNoviRevers = new FrmNoviRevers(this, true);
		frmNoviRevers.setLocationRelativeTo(null);
		frmNoviRevers.setVisible(true);
	}// GEN-LAST:event_miKreirajNoviReversActionPerformed

	private void miKreirajNovogRadnikaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_miKreirajNovogRadnikaActionPerformed
		FrmNoviRadnik frmNoviRadnik = new FrmNoviRadnik(this, true);
		frmNoviRadnik.setLocationRelativeTo(null);
		frmNoviRadnik.setVisible(true);
	}// GEN-LAST:event_miKreirajNovogRadnikaActionPerformed

	private void miKreirajNovuMasinuIliAlatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_miKreirajNovuMasinuIliAlatActionPerformed
		FrmNovaMasinaIliAlat frmNovaMasinaIliAlat = new FrmNovaMasinaIliAlat(this, true);
		frmNovaMasinaIliAlat.setLocationRelativeTo(null);
		frmNovaMasinaIliAlat.setVisible(true);
	}// GEN-LAST:event_miKreirajNovuMasinuIliAlatActionPerformed

	private void miPrikaziSveRadnikeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_miPrikaziSveRadnikeActionPerformed
		FrmRadnici frmRadnici = new FrmRadnici(this, true);
		frmRadnici.setLocationRelativeTo(null);
		frmRadnici.setVisible(true);
	}// GEN-LAST:event_miPrikaziSveRadnikeActionPerformed

	private void miPrikaziSveMasineIliAlatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_miPrikaziSveMasineIliAlatActionPerformed
		FrmMasineIliAlat frmMasineIliAlat = new FrmMasineIliAlat(this, true);
		frmMasineIliAlat.setLocationRelativeTo(null);
		frmMasineIliAlat.setVisible(true);
	}// GEN-LAST:event_miPrikaziSveMasineIliAlatActionPerformed

	private void miPrikaziSveReverseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_miPrikaziSveReverseActionPerformed
		FrmReversi frmReversi = new FrmReversi(this, true);
		frmReversi.setLocationRelativeTo(null);
		frmReversi.setVisible(true);
	}// GEN-LAST:event_miPrikaziSveReverseActionPerformed

	/**
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JLabel lblSlika;
	private javax.swing.JMenu mMasinaIliAlat;
	private javax.swing.JMenu mRadnik;
	private javax.swing.JMenu mi;
	private javax.swing.JMenuItem miKreirajNoviRevers;
	private javax.swing.JMenuItem miKreirajNovogRadnika;
	private javax.swing.JMenuItem miKreirajNovuMasinuIliAlat;
	private javax.swing.JMenuItem miPrikaziSveMasineIliAlat;
	private javax.swing.JMenuItem miPrikaziSveRadnike;
	private javax.swing.JMenuItem miPrikaziSveReverse;
	// End of variables declaration//GEN-END:variables

	private void postaviSliku() {
		slika = new ImageIcon("pictures/magacin.jpg");
		lblSlika.setIcon(slika);
	}

}
