/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view;

import rs.ac.bg.fon.ps.controller.Controller;
import rs.ac.bg.fon.ps.domain.MasinaIliAlat;
import javax.swing.JOptionPane;

/**
 *
 * @author nikolinatomasevic
 */
public class FrmNovaMasinaIliAlat extends javax.swing.JDialog {

	/**
	 * Creates new form FrmNewMasinaIliAlat
	 */
	public FrmNovaMasinaIliAlat(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		lblNaziv = new javax.swing.JLabel();
		txtNaziv = new javax.swing.JTextField();
		lblKolicinaUMagacinu = new javax.swing.JLabel();
		txtKolicinaUMagacinu = new javax.swing.JTextField();
		lblKolicinaNaZaduzenju = new javax.swing.JLabel();
		txtKolicinaNaZaduzenju = new javax.swing.JTextField();
		btnSacuvaj = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Kreiranje Nove Masine Ili Alata");
		setMinimumSize(new java.awt.Dimension(460, 332));

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Masina ili Alat",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 0, 15))); // NOI18N

		lblNaziv.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		lblNaziv.setText("* Naziv:");

		txtNaziv.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

		lblKolicinaUMagacinu.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		lblKolicinaUMagacinu.setText("Kolicina u magacinu:");

		txtKolicinaUMagacinu.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		txtKolicinaUMagacinu.setText("0");

		lblKolicinaNaZaduzenju.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		lblKolicinaNaZaduzenju.setText("Kolicina na zaduzenju:");

		txtKolicinaNaZaduzenju.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		txtKolicinaNaZaduzenju.setText("0");

		btnSacuvaj.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		btnSacuvaj.setText("Sacuvaj");
		btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSacuvajActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(lblNaziv, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(lblKolicinaUMagacinu, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(lblKolicinaNaZaduzenju, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(btnSacuvaj, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(txtKolicinaNaZaduzenju, javax.swing.GroupLayout.DEFAULT_SIZE, 211,
										Short.MAX_VALUE)
								.addComponent(txtKolicinaUMagacinu, javax.swing.GroupLayout.DEFAULT_SIZE, 211,
										Short.MAX_VALUE)
								.addComponent(txtNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
						.addContainerGap(28, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblKolicinaUMagacinu, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtKolicinaUMagacinu, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblKolicinaNaZaduzenju, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtKolicinaNaZaduzenju, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		jLabel1.setText("Polja oznacena zvezdicom su obavezna.");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createSequentialGroup().addComponent(jLabel1).addGap(0, 0, Short.MAX_VALUE)))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSacuvajActionPerformed
		try {
			MasinaIliAlat novaMasinaIliAlat = new MasinaIliAlat();
			novaMasinaIliAlat.setNaziv(txtNaziv.getText().trim());
			if (!txtKolicinaUMagacinu.getText().trim().isEmpty()) {
				novaMasinaIliAlat.setKolicinaUMagacinu(Integer.parseInt(txtKolicinaUMagacinu.getText().trim()));
			}
			if (!txtKolicinaNaZaduzenju.getText().trim().isEmpty()) {
				novaMasinaIliAlat.setKolicinaNaZaduzenju(Integer.parseInt(txtKolicinaNaZaduzenju.getText().trim()));
			}
			Controller.getInstance().zapamtiMasinuIliAlat(novaMasinaIliAlat);
			JOptionPane.showMessageDialog(this, "Sistem je zapamtio masinu ili alat.", "Info",
					JOptionPane.INFORMATION_MESSAGE);
			this.dispose();
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_btnSacuvajActionPerformed

	/**
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnSacuvaj;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JLabel lblKolicinaNaZaduzenju;
	private javax.swing.JLabel lblKolicinaUMagacinu;
	private javax.swing.JLabel lblNaziv;
	private javax.swing.JTextField txtKolicinaNaZaduzenju;
	private javax.swing.JTextField txtKolicinaUMagacinu;
	private javax.swing.JTextField txtNaziv;
	// End of variables declaration//GEN-END:variables

}
