/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view;

import rs.ac.bg.fon.ps.controller.Controller;
import rs.ac.bg.fon.ps.domain.MasinaIliAlat;
import rs.ac.bg.fon.ps.domain.Radnik;
import rs.ac.bg.fon.ps.domain.Revers;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import rs.ac.bg.fon.ps.view.components.TableModelNoveStavkeReversa;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author ACER
 */
public class FrmNoviRevers extends javax.swing.JDialog {

	/**
	 * Creates new form FrmRevers
	 */

	private final Revers revers;
	SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");

	public FrmNoviRevers(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		revers = new Revers();
		try {
			pripremiFormu();
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		lbl1 = new javax.swing.JLabel();
		lblRadnik = new javax.swing.JLabel();
		cmbRadnik = new javax.swing.JComboBox();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblStavke = new javax.swing.JTable();
		btnIzbrisiStavku = new javax.swing.JButton();
		btnSacuvajRevers = new javax.swing.JButton();
		btnDodajNovuStavku = new javax.swing.JButton();
		lblDatumIzdavanja = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Kreiranje Novog Reversa");
		setMinimumSize(new java.awt.Dimension(732, 382));

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Revers",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 0, 15))); // NOI18N

		lbl1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		lbl1.setText("Datum izdavanja:");

		lblRadnik.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		lblRadnik.setText("Radnik:");

		cmbRadnik.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

		tblStavke.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		tblStavke.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "RB", "Zaduzena kolicina", "Masina ili Alat" }));
		jScrollPane1.setViewportView(tblStavke);

		btnIzbrisiStavku.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		btnIzbrisiStavku.setText("Izbrisi stavku");
		btnIzbrisiStavku.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnIzbrisiStavkuActionPerformed(evt);
			}
		});

		btnSacuvajRevers.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		btnSacuvajRevers.setText("Sacuvaj revers");
		btnSacuvajRevers.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSacuvajReversActionPerformed(evt);
			}
		});

		btnDodajNovuStavku.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		btnDodajNovuStavku.setText("Dodaj novu stavku");
		btnDodajNovuStavku.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDodajNovuStavkuActionPerformed(evt);
			}
		});

		lblDatumIzdavanja.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel1Layout
				.createSequentialGroup().addContainerGap()
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
						.addComponent(btnSacuvajRevers, GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
										.addComponent(lblRadnik, GroupLayout.PREFERRED_SIZE, 115,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(lbl1))
								.addGap(46)
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
										.addComponent(cmbRadnik, 0, 356, Short.MAX_VALUE).addComponent(
												lblDatumIzdavanja, GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))))
				.addGap(18)
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
						.addComponent(btnIzbrisiStavku, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addComponent(btnDodajNovuStavku, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE))
				.addGap(20)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(lblDatumIzdavanja, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 32,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(lbl1, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
						.addGap(18)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(lblRadnik, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
								.addComponent(cmbRadnik, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
						.addGap(35)
						.addGroup(
								jPanel1Layout.createParallelGroup(Alignment.TRAILING)
										.addGroup(jPanel1Layout.createSequentialGroup()
												.addComponent(btnDodajNovuStavku, GroupLayout.PREFERRED_SIZE, 32,
														GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(ComponentPlacement.RELATED)
												.addComponent(btnIzbrisiStavku, GroupLayout.PREFERRED_SIZE, 32,
														GroupLayout.PREFERRED_SIZE)
												.addGap(12))
										.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 111,
												GroupLayout.PREFERRED_SIZE))
						.addGap(18)
						.addComponent(btnSacuvajRevers, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(25, Short.MAX_VALUE)));
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnDodajNovuStavkuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDodajNovuStavkuActionPerformed
		TableModelNoveStavkeReversa tm = (TableModelNoveStavkeReversa) tblStavke.getModel();
		tm.dodajNovuStavku();
	}// GEN-LAST:event_btnDodajNovuStavkuActionPerformed

	private void btnIzbrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnIzbrisiStavkuActionPerformed
		TableModelNoveStavkeReversa tm = (TableModelNoveStavkeReversa) tblStavke.getModel();
		int red = tblStavke.getSelectedRow();
		if (red != -1) {
			tm.ObrisiStavku(red);
		}
	}// GEN-LAST:event_btnIzbrisiStavkuActionPerformed

	private void btnSacuvajReversActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSacuvajReversActionPerformed
		try {
			try {
				revers.setDatumIzdavanja(sdf.parse(lblDatumIzdavanja.getText().trim()));
			} catch (ParseException ex) {
				throw new Exception("Datum mora biti u formatu 'dd.MM.yyyy.'");
			}
			revers.setRadnik((Radnik) cmbRadnik.getSelectedItem());
			Controller.getInstance().zapamtiRevers(revers);
			JOptionPane.showMessageDialog(this, "Sistem je zapamtio revers.");
			this.dispose();
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_btnSacuvajReversActionPerformed

	/**
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnDodajNovuStavku;
	private javax.swing.JButton btnIzbrisiStavku;
	private javax.swing.JButton btnSacuvajRevers;
	private javax.swing.JComboBox cmbRadnik;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lbl1;
	private javax.swing.JLabel lblDatumIzdavanja;
	private javax.swing.JLabel lblRadnik;
	private javax.swing.JTable tblStavke;
	// End of variables declaration//GEN-END:variables

	private void pripremiFormu() throws Exception {
		lblDatumIzdavanja.setText(sdf.format(new Date()));
		pripremiCmbRadnik();
		pripremitblStavke();
	}

	private void pripremiCmbRadnik() throws Exception {
		List<Radnik> radnici = Controller.getInstance().ucitajListuRadnika();
		cmbRadnik.removeAllItems();
		for (Radnik radnik : radnici) {
			cmbRadnik.addItem(radnik);
		}
	}

	private void pripremitblStavke() throws Exception {
		TableModelNoveStavkeReversa tm = new TableModelNoveStavkeReversa(revers);
		tblStavke.setModel(tm);

		List<MasinaIliAlat> masine = Controller.getInstance().ucitajListuMasinaIliAlata();
		JComboBox cmbMasinaIliAlat = new JComboBox(masine.toArray());
		TableColumn clmnMasinaIliAlat = tblStavke.getColumnModel().getColumn(2);
		clmnMasinaIliAlat.setCellEditor(new DefaultCellEditor(cmbMasinaIliAlat));
	}

}
