/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view;

import rs.ac.bg.fon.ps.controller.Controller;
import rs.ac.bg.fon.ps.domain.Radnik;
import rs.ac.bg.fon.ps.domain.RadnoMesto;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author nikolinatomasevic
 */
public class FrmPromeniRadnika extends javax.swing.JDialog {

	/**
	 * Creates new form FrmNewRadnik
	 */

	public FrmPromeniRadnika(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		try {
			pripremiFormu();
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		lbl2 = new javax.swing.JLabel();
		txtIme = new javax.swing.JTextField();
		lbl3 = new javax.swing.JLabel();
		txtPrezime = new javax.swing.JTextField();
		lbl4 = new javax.swing.JLabel();
		txtBrojTelefona = new javax.swing.JTextField();
		lbl5 = new javax.swing.JLabel();
		txtMejl = new javax.swing.JTextField();
		lblRadnoMestoCmb = new javax.swing.JLabel();
		cmbRadnoMesto = new javax.swing.JComboBox();
		btnSacuvajPromene = new javax.swing.JButton();
		lbl1 = new javax.swing.JLabel();
		lblID = new javax.swing.JLabel();
		lblRadnoMestoLbl = new javax.swing.JLabel();
		lblRadnoMesto = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Promena Podataka Radnika");
		setMinimumSize(new java.awt.Dimension(502, 512));

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Radnik",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 0, 15))); // NOI18N

		lbl2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		lbl2.setText("* Ime:");

		txtIme.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

		lbl3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		lbl3.setText("* Prezime:");

		txtPrezime.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

		lbl4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		lbl4.setText("  Broj telefona:");

		txtBrojTelefona.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

		lbl5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		lbl5.setText("* Mejl:");

		txtMejl.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

		lblRadnoMestoCmb.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		lblRadnoMestoCmb.setText("* Radno mesto:");

		cmbRadnoMesto.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

		btnSacuvajPromene.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		btnSacuvajPromene.setText("Sacuvaj promene");
		btnSacuvajPromene.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSacuvajPromeneActionPerformed(evt);
			}
		});

		lbl1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		lbl1.setText("  ID:");

		lblID.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

		lblRadnoMestoLbl.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		lblRadnoMestoLbl.setText("  Radno mesto:");

		lblRadnoMesto.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
										.addComponent(lbl1, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(txtPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 303,
														Short.MAX_VALUE)
												.addComponent(txtIme).addComponent(lblID,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(lbl4, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(lbl5, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(lblRadnoMestoCmb, javax.swing.GroupLayout.DEFAULT_SIZE,
														109, Short.MAX_VALUE)
												.addComponent(
														lblRadnoMestoLbl, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addGap(18, 18, 18)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(btnSacuvajPromene,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
												.addComponent(txtBrojTelefona).addComponent(txtMejl)
												.addComponent(cmbRadnoMesto, javax.swing.GroupLayout.Alignment.TRAILING,
														0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(lblRadnoMesto, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
						.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtBrojTelefona, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtMejl, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblRadnoMestoCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(cmbRadnoMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(lblRadnoMestoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblRadnoMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addComponent(btnSacuvajPromene, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		jLabel1.setText("Polja oznacena zvezdicom su obavezna.");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel1).addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnSacuvajPromeneActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSacuvajPromeneActionPerformed
		try {
			Radnik radnik = new Radnik();
			radnik.setRadnikID(Long.valueOf(lblID.getText()));
			radnik.setIme(txtIme.getText().trim());
			radnik.setPrezime(txtPrezime.getText().trim());
			if (!txtBrojTelefona.getText().trim().isEmpty()) {
				radnik.setBrojTelefona(txtBrojTelefona.getText().trim());
			}
			radnik.setMejl(txtMejl.getText().trim());
			if (cmbRadnoMesto.isVisible()) {
				radnik.setRadnoMesto((RadnoMesto) cmbRadnoMesto.getSelectedItem());
			} else {
				radnik.setRadnoMesto(new RadnoMesto(1l, "Radnik u magacinu"));
			}
			Controller.getInstance().promeniRadnika(radnik);
			JOptionPane.showMessageDialog(this, "Sistem je zapamtio radnika.", "Info", JOptionPane.INFORMATION_MESSAGE);
			this.dispose();
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_btnSacuvajPromeneActionPerformed

	/**
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnSacuvajPromene;
	private javax.swing.JComboBox cmbRadnoMesto;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JLabel lbl1;
	private javax.swing.JLabel lbl2;
	private javax.swing.JLabel lbl3;
	private javax.swing.JLabel lbl4;
	private javax.swing.JLabel lbl5;
	private javax.swing.JLabel lblID;
	private javax.swing.JLabel lblRadnoMesto;
	private javax.swing.JLabel lblRadnoMestoCmb;
	private javax.swing.JLabel lblRadnoMestoLbl;
	private javax.swing.JTextField txtBrojTelefona;
	private javax.swing.JTextField txtIme;
	private javax.swing.JTextField txtMejl;
	private javax.swing.JTextField txtPrezime;
	// End of variables declaration//GEN-END:variables

	private void pripremiFormu() throws Exception {
		cmbRadnoMesto.removeAllItems();
		List<RadnoMesto> radnaMesta = Controller.getInstance().ucitajListuRadnihMesta();
		radnaMesta.remove(0);
		for (RadnoMesto radnoMesto : radnaMesta) {
			cmbRadnoMesto.addItem(radnoMesto);
		}
	}

	public void setRadnik(Radnik radnik) {
		lblID.setText(String.valueOf(radnik.getRadnikID()));
		txtIme.setText(radnik.getIme());
		txtPrezime.setText(radnik.getPrezime());
		txtBrojTelefona.setText(radnik.getBrojTelefona());
		txtMejl.setText(radnik.getMejl());
		if (radnik.getRadnoMesto().equals(new RadnoMesto(1l, "Radnik u magacinu"))) {
			lblRadnoMestoCmb.setVisible(false);
			cmbRadnoMesto.setVisible(false);
			lblRadnoMesto.setText(String.valueOf(radnik.getRadnoMesto()));
		} else {
			lblRadnoMestoLbl.setVisible(false);
			lblRadnoMesto.setVisible(false);
			cmbRadnoMesto.setSelectedItem(radnik.getRadnoMesto());
		}
	}

}
