/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view;

import rs.ac.bg.fon.ps.controller.Controller;
import rs.ac.bg.fon.ps.domain.Revers;
import rs.ac.bg.fon.ps.domain.StavkaReversa;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.ps.domain.MasinaIliAlat;
import rs.ac.bg.fon.ps.domain.Radnik;
import rs.ac.bg.fon.ps.view.components.TableModelReversi;

/**
 *
 * @author ACER
 */
public class FrmReversi extends javax.swing.JDialog {

	/**
	 * Creates new form FrmReversi
	 */

	public FrmReversi(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		try {
			pripremiTabeluReversa();
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txtIme = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		txtPrezime = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		txtNaziv = new javax.swing.JTextField();
		btnPretrazi = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		btnDetaljnije = new javax.swing.JButton();
		btnKreirajNoviRevers = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		tblReversi = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Reversi");
		setMinimumSize(new java.awt.Dimension(882, 562));
		addWindowFocusListener(new java.awt.event.WindowFocusListener() {
			public void windowGainedFocus(java.awt.event.WindowEvent evt) {
				formWindowGainedFocus(evt);
			}

			public void windowLostFocus(java.awt.event.WindowEvent evt) {
			}
		});

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
		jLabel1.setText("Pretrazi reverse po vrednostima:");

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		jLabel2.setText("ime radnika:");

		txtIme.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

		jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		jLabel5.setText("prezime radnika:");

		txtPrezime.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

		jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		jLabel6.setText("naziv masine:");

		txtNaziv.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

		btnPretrazi.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		btnPretrazi.setText("Pretrazi");
		btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnPretraziActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		jLabel4.setText("Reversi:");

		btnDetaljnije.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		btnDetaljnije.setText("Detaljnije");
		btnDetaljnije.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDetaljnijeActionPerformed(evt);
			}
		});

		btnKreirajNoviRevers.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		btnKreirajNoviRevers.setText("Kreiraj novi revers");
		btnKreirajNoviRevers.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnKreirajNoviReversActionPerformed(evt);
			}
		});

		tblReversi.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Broj reversa", "Radnik", "RB stavke", "Zaduzena kolicina", "Masina ili alat" }));
		jScrollPane2.setViewportView(tblReversi);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap().addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 794,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(btnDetaljnije, javax.swing.GroupLayout.PREFERRED_SIZE, 173,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btnKreirajNoviRevers, javax.swing.GroupLayout.PREFERRED_SIZE, 173,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addGroup(layout.createSequentialGroup().addComponent(jLabel5).addGap(18, 18, 18)
										.addComponent(txtPrezime))
								.addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
										layout.createSequentialGroup()
												.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18).addComponent(txtIme)))
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 107,
												Short.MAX_VALUE))
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(btnPretrazi, javax.swing.GroupLayout.DEFAULT_SIZE, 194,
												Short.MAX_VALUE)
										.addComponent(txtNaziv))))
						.addContainerGap(20, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addComponent(
						jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(14, 14, 14)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(26, 26, 26)
				.addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18)
				.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(45, 45, 45)
								.addComponent(btnDetaljnije, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(
										btnKreirajNoviRevers, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup().addGap(18, 18, 18).addComponent(jScrollPane2,
								javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addContainerGap(20, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPretraziActionPerformed
		TableModelReversi model = (TableModelReversi) tblReversi.getModel();
		String ime = txtIme.getText().trim();
		String prezime = txtPrezime.getText().trim();
		Radnik radnik = new Radnik();
		radnik.setIme(ime);
		radnik.setPrezime(prezime);
		String naziv = txtNaziv.getText().toLowerCase().trim();
		MasinaIliAlat masinaIliAlat = new MasinaIliAlat();
		masinaIliAlat.setNaziv(naziv);
		Revers r = new Revers();
		r.setRadnik(radnik);
		StavkaReversa stavka = new StavkaReversa();
		stavka.setMasinaIliAlat(masinaIliAlat);
		r.getStavke().add(stavka);

		List<StavkaReversa> trazeneStavke = new ArrayList<>();
		try {
			trazeneStavke = Controller.getInstance().nadjiStavkeReversa(r);
			JOptionPane.showMessageDialog(this, "Sistem je nasao reverse po zadatoj vrednosti.", "Info",
					JOptionPane.INFORMATION_MESSAGE);
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
		}
		model.setSveStavke(trazeneStavke);
		btnPretrazi.setSelected(true);
	}// GEN-LAST:event_btnPretraziActionPerformed

	private void btnDetaljnijeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDetaljnijeActionPerformed
		TableModelReversi model = (TableModelReversi) tblReversi.getModel();
		int row = tblReversi.getSelectedRow();
		if (row != -1) {
			StavkaReversa stavka = model.getSelectedStavka(row);
			FrmPromeniRevers frmPromeni = new FrmPromeniRevers((FrmMain) this.getParent(), true);
			frmPromeni.setStavka(stavka);
			frmPromeni.setLocationRelativeTo(null);
			JOptionPane.showMessageDialog(this, "Sistem je ucitao revers.", "Info", JOptionPane.INFORMATION_MESSAGE);
			frmPromeni.setVisible(true);
		}
	}// GEN-LAST:event_btnDetaljnijeActionPerformed

	private void btnKreirajNoviReversActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnKreirajNoviReversActionPerformed
		FrmNoviRevers frmNoviRevers = new FrmNoviRevers((JFrame) this.getParent(), true);
		frmNoviRevers.setLocationRelativeTo(null);
		frmNoviRevers.setVisible(true);
	}// GEN-LAST:event_btnKreirajNoviReversActionPerformed

	private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowGainedFocus
		if (btnPretrazi.isSelected()) {
			btnPretrazi.setSelected(false);
		} else {
			TableModelReversi model = (TableModelReversi) tblReversi.getModel();
			try {
				List<Revers> reversi = Controller.getInstance().ucitajListuReversa();
				model.setReversi(reversi);
				txtIme.setText("");
				txtPrezime.setText("");
				txtNaziv.setText("");
			} catch (Exception ex) {
				JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
			}
		}
	}// GEN-LAST:event_formWindowGainedFocus

	/**
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnDetaljnije;
	private javax.swing.JButton btnKreirajNoviRevers;
	private javax.swing.JButton btnPretrazi;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable tblReversi;
	private javax.swing.JTextField txtIme;
	private javax.swing.JTextField txtNaziv;
	private javax.swing.JTextField txtPrezime;
	// End of variables declaration//GEN-END:variables

	private void pripremiTabeluReversa() throws Exception {
		List<Revers> reversi = Controller.getInstance().ucitajListuReversa();
		TableModelReversi model = new TableModelReversi(reversi);
		tblReversi.setModel(model);
	}
}
